"""create_jobs_table

Revision ID: d186a4902c34
Revises:
Create Date: 2026-04-21 14:52:14.801911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd186a4902c34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('description_snippet', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('notified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_created_at'), 'vacancies', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancies_external_id'), 'vacancies', ['external_id'], unique=True)
    op.create_index('ix_vacancies_notified_false', 'vacancies', ['notified'], unique=False, postgresql_where=sa.text('notified = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_notified_false', table_name='vacancies', postgresql_where=sa.text('notified = false'))
    op.drop_index(op.f('ix_vacancies_external_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_created_at'), table_name='vacancies')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
